spring.application.name=lunch-box

spring.datasource.url = jdbc:postgresql://localhost:5432/lunch_box
spring.datasource.username = postgres
spring.datasource.password = 1234

spring.jpa.hibernate.ddl-auto = update
spring.jpa.database_platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
spring.app.jwtSecret=mySecretKeyForJWTTokenGenerationPleaseChangeThisInProduction1234567890
spring.app.jwtAccessTokenExpirationMs=60000
spring.app.jwtRefreshTokenExpirationMs=120000
spring.ecom.app.jwtCookieName=lunchbox-jwt

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com
app.oauth.google.client-id=786529147013-rn89uc8m50em0l0v7fh8i04tcl547hgg.apps.googleusercontent.com
#google.android-client-id=786529147013-rn89uc8m50em0l0v7fh8i04tcl547hgg.apps.googleusercontent.com

# Tell SpringDoc exactly where your controllers are
springdoc.packages-to-scan=com.lunchbox.lunch_box.modules
