spring.application.name=lunch-box

spring.datasource.url = jdbc:postgresql://localhost:5432/lunch_box
spring.datasource.username = postgres
spring.datasource.password = admin

spring.jpa.hibernate.ddl-auto = update
spring.jpa.database_platform = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
spring.app.jwtSecret=mySecretKeyForJWTTokenGenerationPleaseChangeThisInProduction1234567890
spring.app.jwtAccessTokenExpirationMs=3600000
spring.app.jwtRefreshTokenExpirationMs=86400000
spring.ecom.app.jwtCookieName=lunchbox-jwt
